language: csharp
dotnet: 1.0.0-preview2-003131
mono: none

matrix:
  include:
    - os: linux
    - os: osx

script:
  - dotnet restore
  - dotnet build **/*/project.json
  - dotnet test tests/Mercurial.Client.Tests/project.json
