language: csharp

matrix:
  include:
  - os: linux
    dist: trusty # Ubuntu 14.04
    dotnet: 1.0.0-preview3-004056 
    mono: none
    sudo: required
  - os: osx
    osx_image: xcode7.3 # macOS 10.11
    dotnet: 1.0.0-preview3-004056
    mono: none

install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1

script:
  - dotnet restore
  - dotnet build **/*/project.json
  - dotnet test tests/Mercurial.Client.Tests/project.json
