language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-1-003177
    - os: osx # OSX 10.11
      osx_image: xcode7.2
      dotnet: 1.0.0-preview2-1-003177

script:
  # Run a new console app
  - dotnet restore
  - dotnet build **/*/project.json
  - dotnet test tests/Mercurial.Client.Tests/project.json
