# version format
version: 1.0.0.{build}

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Build worker image (VM template)
image: Visual Studio 2015

# build cache to preserve files/folders between builds
cache:
  - packages

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# scripts that run after cloning repository
install:
  # remove this when nuget 3.5 will be available on appveyor
  - ps: Start-FileDownload "https://dist.nuget.org/win-x86-commandline/v3.5.0-beta/NuGet.exe"

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

before_build:
  - nuget restore
  - ps: .\build\version.ps1

build:
  parallel: false                  # enable MSBuild parallel builds
  project: Mercurial.Client.sln    # path to Visual Studio solution or project
  publish_nuget: false             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: false     # generate and publish NuGet symbol packages

after_build:
  - dotnet pack .\src\Mercurial.Client\project.json --configuration Release

test_script:
  - dotnet test .\tests\Mercurial.Client.Tests\project.json --configuration Release -xml tests-results01.xml
  - ps: .\build\uploadtests.ps1 "tests-results01.xml"

artifacts:
  - path: '**\Mercurial.Client.*.nupkg' # find all NuGet packages recursively
